on:
  workflow_dispatch:

jobs:
  sonar:
    name: SonarCloud Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install HashiCorp Vault CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install vault -y

      - name: Authenticate with HashiCorp Vault
        env:
          VAULT_ADDR: https://vault-cluster-public-vault-01328c14.45ec0be2.z1.hashicorp.cloud:8200
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: vault login -no-print $VAULT_TOKEN

      - name: Set up Vault Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: "https://vault-cluster-public-vault-01328c14.45ec0be2.z1.hashicorp.cloud:8200"
          token: ${{ secrets.VAULT_TOKEN }}
          path: pshara6644-org/pshara6644-project/Vault Secrets/Applications/sample-test/Secrets
          key: SONAR_TOKEN

      - name: Set SonarCloud Environment Variable
        run: |
          echo "SONAR_TOKEN=${{ steps.retrieve_vault_secret.outputs.value }}" >> $GITHUB_ENV

      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ env.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_quality:
    name: Check Sonar Report Quality
    runs-on: ubuntu-latest
    needs: sonar
    env:
      CODE_SMELLS_THRESHOLD: "16"
      VULNERABILITIES_THRESHOLD: "0"
      BUGS_THRESHOLD: "0"
    steps:
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Retrieve SonarCloud Metrics
        id: retrieve_metrics
        run: |
          SONAR_RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
                          "https://sonarcloud.io/api/measures/component?component=Shara-org_sample-java-repo&metricKeys=code_smells,vulnerabilities,bugs")
          echo "::set-output name=sonar_response::$SONAR_RESPONSE"

      - name: Check Sonar Report
        run: |
          SONAR_RESPONSE="${{ steps.retrieve_metrics.outputs.sonar_response }}"
          CODE_SMELLS=$(echo "$SONAR_RESPONSE" | jq -r '.component.measures[] | select(.metric == "code_smells") | .value')
          VULNERABILITIES=$(echo "$SONAR_RESPONSE" | jq -r '.component.measures[] | select(.metric == "vulnerabilities") | .value')
          BUGS=$(echo "$SONAR_RESPONSE" | jq -r
