
name: "java_app_pipeline"

on:
  push:
   branches: [ feature ]
   # branches: [ main, develop, "feature/*", "hotfix/*", "release/*" ]

jobs:
  
  Codebuild:
    name: Codebuild
    uses: "./.github/workflows/Build_Stage.yml"
    with:
       runnerName: "ubuntu-latest"
       java-version: "11"
       distribution: "temurin"
       cache: "maven" 
  docker:
      name: Publish - Docker Hub
      runs-on: ubuntu-latest
      needs: [ Codebuild ]
      env:
       REPO: ${{ secrets.DOCKER_REPO }}

      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
           java-version: 11.0.4
        - name: Login to Docker Hub
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        - name: Build Docker image
          run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
        - name: Publish Docker image
          run: docker push $REPO
       
  BuildImageandTrivyScanner:
      name: Trivyscanner
      uses: "./.github/workflows/trivy.yml"
      needs: [ Codebuild ]     
 # CodeScanning:
  #    name: Test - SonarCloud Scan
 #     uses: "./.github/workflows/Code_Quality_Stage.yml"
 #     needs: [ Codebuild ]
  ##        java-version : "11.0.4"
  # #      runnerName: "ubuntu-latest"
          
  #buildImageandDeploy:
  #    name: building docker image
      
  #    needs: [ Codebuild , CodeScanning]
  #    uses: "./.github/workflows/deploystage.yml"
  #    with:
  #      runnerName: "ubuntu-latest"
      
