on:
  workflow_call:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.42.1/trivy_0.42.1_Linux-64bit.tar.gz
          tar zxvf trivy_0.42.1_Linux-64bit.tar.gz
          export PATH=$(pwd)/trivy_0.42.1_Linux-64bit:$PATH

      - name: Run Trivy scan
        run: trivy image --clear-cache --exit-code 1 ${{ env.REPO }}:${{ github.sha }}
