on:
  workflow_call:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      
    
     - name: Install Trivy
       run: |
           wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.deb
           sudo dpkg -i trivy_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.deb

     - name: Run Trivy scan
       run: trivy image --clear-cache --exit-code 1 ${{ env.REPO }}:${{ github.sha }}
