on:
  workflow_call:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      
    
     - name: Install Trivy
       run: |
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

     - name: Run Trivy scan
       run: trivy image --clear-cache --exit-code 1 ${{ env.REPO }}:${{ github.sha }}
