on:
  workflow_call:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
       REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
           image-ref: '${{ env.REPO }}:${{ github.sha }}'
           format: 'table'
           exit-code: '1'
           ignore-unfixed: true
           vuln-type: 'os,library'
           severity: 'CRITICAL,HIGH'
